FROM node:20-alpine AS base
ENV PNPM_HOME="/pnpm"
ENV PATH="$PNPM_HOME:$PATH"
RUN corepack enable

# Builder
FROM base AS builder
WORKDIR /app
COPY . .
RUN pnpm install --frozen-lockfile
RUN pnpm --filter @onm/db generate
RUN pnpm --filter worker build
RUN pnpm deploy --filter=worker --prod /prod/worker

# Runner
FROM base AS runner
WORKDIR /app
COPY --from=builder /prod/worker /app

ENV NODE_ENV=production

CMD ["node", "dist/index.js"]
