import type { FixProposalOutputType } from "../schemas.js";

/**
 * Fix Proposal Agent - Proposes patches for issues.
 * 
 * TODO: Wire up LLM with repository context to generate patches.
 * For now, returns analysis-only (null patch) requiring manual implementation.
 * 
 * SAFETY: This agent should NEVER auto-merge. Human review is required.
 */
export async function runFixProposal(input: Record<string, unknown>): Promise<FixProposalOutputType> {
    const title = String(input.title || "");
    const body = String(input.body || "");
    const labels = Array.isArray(input.labels) ? input.labels : [];

    return {
        analysis_md: `## Issue Analysis

### Context
- **Title:** ${title.slice(0, 100)}
- **Labels:** ${labels.join(", ") || "None"}

### Assessment
This issue requires LLM integration to generate a fix proposal.

### Why No Patch?
The gateway is running in stub mode. To enable AI-powered patch generation:
1. Connect your preferred LLM (OpenAI, Claude, Gemini)
2. Provide repository context (file structure, relevant code)
3. Implement appropriate safety guards

### Manual Action Required
Please review the issue manually and implement a fix if appropriate.

---
*Human-in-the-loop: AI cannot auto-merge. All changes require maintainer approval.*`,
        risk: "high", // High risk without proper LLM analysis
        confidence: 0.1, // Very low without LLM
        patch_unified_diff: null, // No patch in stub mode
        pr_title: `fix: Address issue - ${title.slice(0, 80)}`,
        pr_body: `## Summary
Addresses: ${title}

## Changes
- (Pending LLM implementation)

## Testing
- (Pending)

---
*Generated by AI Gateway stub. Connect LLM for actual fix proposals.*`,
    };
}
