name: Bug Report
description: Report a reproducible bug in plugin / api / web.
title: "[Bug]: "
labels: ["type:bug"]
body:
  - type: markdown
    attributes:
      value: "Thanks for reporting. Please provide enough detail to reproduce."
  - type: dropdown
    id: area
    attributes:
      label: Area
      options:
        - plugin
        - api
        - website
        - licensing
        - unknown
    validations:
      required: true
  - type: dropdown
    id: severity
    attributes:
      label: Severity
      options:
        - critical
        - major
        - minor
    validations:
      required: true
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
    validations:
      required: true
  - type: textarea
    id: repro
    attributes:
      label: Reproduction Steps
      description: Step-by-step instructions.
      placeholder: |
        1) ...
        2) ...
        3) ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
    validations:
      required: true
  - type: input
    id: obsidian
    attributes:
      label: Obsidian Version
      placeholder: "e.g. 1.6.7"
  - type: input
    id: plugin
    attributes:
      label: Plugin Version
      placeholder: "e.g. 1.0.0-commercial"
  - type: input
    id: os
    attributes:
      label: OS
      placeholder: "Windows / macOS / Linux / iOS / Android"
  - type: textarea
    id: logs
    attributes:
      label: Logs (optional)
      description: Remove any personal data before pasting.
      render: shell
