name: Feature Request
description: Suggest an improvement.
title: "[Feature]: "
labels: ["type:feature"]
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem / Motivation
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
