name: Question
description: Ask a usage question.
title: "[Question]: "
labels: ["type:question"]
body:
  - type: textarea
    id: question
    attributes:
      label: Question
    validations:
      required: true
  - type: input
    id: obsidian
    attributes:
      label: Obsidian Version
  - type: input
    id: plugin
    attributes:
      label: Plugin Version
